# Generated by Django 4.1.4 on 2023-03-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_recipe_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_comment', models.CharField(max_length=255, verbose_name='Título do comentário:')),
                ('email_comment', models.EmailField(max_length=254, verbose_name='E-mail:')),
                ('comment', models.TextField(verbose_name='Comentário:')),
                ('datatime_comment', models.DateTimeField(auto_now_add=True)),
                ('published_comment', models.BooleanField(default=False)),
                ('recipe_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
